# Generated by Django 4.2 on 2023-04-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_customer_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_account',
            name='mobiel_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
