# Generated by Django 4.2 on 2023-04-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0005_customer_account_mobiel_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_account',
            old_name='mobiel_number',
            new_name='mobile_number',
        ),
    ]
