# Generated by Django 4.2 on 2023-04-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
