# Generated by Django 4.2 on 2023-04-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0011_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
